[package]
name = "dnsecho"
version = "0.1.0"
authors = ["zhanglei <zhanglei@zdns.cn>"]
edition = "2018"

[dependencies]
tokio = "0.1"
futures = "0.1"
error-chain = { version = "0.12", default-features = false }
clap = { version = "2.32", default-features = false}
r53 = {path = "../r53"}

